language: python

python:
  - 2.7

virtualenv:
     system_site_packages: false

#There are a few environments configured, we specify a minumum version of mpl
#and a exact version of Numpy to test against.
env:
    - NUMPY_VERSION=1.7.1 MATPLOTLIB_VERSION=1.2 PANDAS_VERSION=0.11.0 SUDS_PKG='suds-jurko'

matrix:
    include:
      - python: 2.6
        env: NUMPY_VERSION=1.7.1 MATPLOTLIB_VERSION=1.2 PANDAS_VERSION=0.11.0 SUDS_PKG='suds'
      - python: 2.7
        env: NUMPY_VERSION=1.6.2 MATPLOTLIB_VERSION=1.2 PANDAS_VERSION=0.11.0 SUDS_PKG='suds-jurko'
      - python: 2.6
        env: NUMPY_VERSION=1.6.2 MATPLOTLIB_VERSION=1.2 PANDAS_VERSION=0.11.0 SUDS_PKG='suds'
      - python: 2.7
        env: NUMPY_VERSION=1.7.1 MATPLOTLIB_VERSION=1.2 PANDAS_VERSION=0.10.1 SUDS_PKG='suds-jurko'
      - python: 2.6
        env: NUMPY_VERSION=1.7.1 MATPLOTLIB_VERSION=1.2 PANDAS_VERSION=0.10.1 SUDS_PKG='suds'

before_install:
   # We do this to make sure we get the dependencies so pip works below
   - sudo apt-get update -qq
   - pip install pip --upgrade

install:
   - pip install setuptools>=0.8 --upgrade
   - pip install wheel --upgrade

# command to run tests
script:
  - pwd;
  - bash make_wheels.sh
  #Pipe to /dev/null to hide decrypted user / pass
  - bash ftp_upload.sh > /dev/null
