language: python
python:
- 2.7
virtualenv:
  system_site_packages: false
env:
  matrix:
  - NUMPY_VERSION=1.7.1 MATPLOTLIB_VERSION=1.2 PANDAS_VERSION=0.11.0 SUDS_PKG='suds-jurko'
  global:
  - secure: ZF8C1Q4soXE3M3GtA8Wh2ptWMi/1alu2ocIFvhYQencPpSjKgDYG2ppwomSigwLuhTRuGh6FtUBaqVg+KR8llxMh7wMhS9oOfmKZ3SG0IgNGRKj1mFDEJqZwqGZZasfmm1OBc6iBt6tCSFk5l/TIUDF6Pw9acvLJHUdACcm2tzA=
  - secure: mjxGsDeQZTtjLM1eRQN8T5FfILTU4IeKGsRi1OVcgms55X8AgmU6e2Z+rha2eQY46ftNjp+EwMThN7iW5BeEfXK89ihWLf2hdEVJePyBjxHQI2NGHtWc1h4EbaebPi8wNcQzTGWJy5mVImIEXv2+y+7lRnboCvquldiiUcnF88g=
matrix:
  include:
  - python: 2.6
    env: NUMPY_VERSION=1.7.1 MATPLOTLIB_VERSION=1.2 PANDAS_VERSION=0.11.0 SUDS_PKG='suds'
  - python: 2.7
    env: NUMPY_VERSION=1.6.2 MATPLOTLIB_VERSION=1.2 PANDAS_VERSION=0.11.0 SUDS_PKG='suds-jurko'
  - python: 2.6
    env: NUMPY_VERSION=1.6.2 MATPLOTLIB_VERSION=1.2 PANDAS_VERSION=0.11.0 SUDS_PKG='suds'
  - python: 2.7
    env: NUMPY_VERSION=1.7.1 MATPLOTLIB_VERSION=1.2 PANDAS_VERSION=0.10.1 SUDS_PKG='suds-jurko'
  - python: 2.6
    env: NUMPY_VERSION=1.7.1 MATPLOTLIB_VERSION=1.2 PANDAS_VERSION=0.10.1 SUDS_PKG='suds'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ftp
  - sudo apt-get install -qq libatlas-dev liblapack-dev gfortran
  - pip install pip --upgrade

install:
  - pip install setuptools>=0.8 --upgrade
  - pip install wheel --upgrade
    # Install NumPy because Astropy needs it to build
  - pip wheel --wheel-dir=./wheelhouse numpy==$NUMPY_VERSION
  - pip install --use-wheel --no-index --find-links=./wheelhouse numpy==$NUMPY_VERSION
    # Also install the latest version of cython
  - pip wheel --wheel-dir=./wheelhouse cython
  - pip install --use-wheel --no-index --find-links=./wheelhouse cython
    # Do scipy here because it takes ages!!
  - pip wheel --wheel-dir=./wheelhouse scipy

script:
  - pwd;
  -	pip wheel --wheel-dir=./wheelhouse matplotlib=>$MATPLOTLIB_VERSION
  - pip wheel --wheel-dir=./wheelhouse pandas==$PANDAS_VERSION
  - pip wheel --wheel-dir=./wheelhouse astropy
  - ls wheelhouse;
  - python make_index.py
  - bash ftp_upload.sh > /dev/null
